[package]
name = "collection"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lib]
path = "src/collection.rs"

[dependencies]
workspace.workspace = true
gpui.workspace = true
ui.workspace = true
