[workspace]
resolver = "2"
members = [
    "crates/*"
]
default-members = ["crates/bridge"]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]

#
# Workspace member crates
#

#
# External crates
#
