[package]
name = "bridge"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
uuid.workspace = true
workspace.workspace = true
collection.workspace = true
settings.workspace = true
http_client.workspace = true
http_editor.workspace = true
title_bar.workspace = true
assets.workspace = true
