[package]
name = "bridge"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
uuid.workspace = true
workspace.workspace = true
theme.workspace = true
collection.workspace = true
settings.workspace = true
