[package]
name = "http_editor"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lib]
path = "src/http_editor.rs"

[dependencies]
gpui.workspace = true
gpui-macros.workspace = true
gpui-component.workspace = true
serde.workspace = true
anyhow.workspace = true
workspace.workspace = true
http_client.workspace = true
humantime.workspace = true
url.workspace = true
regex.workspace = true
indexmap.workspace = true
smallvec.workspace = true
http.workspace = true
