[package]
name = "workspace"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lib]
path = "src/workspace.rs"

[dependencies]
gpui.workspace = true
anyhow.workspace = true
uuid.workspace = true
parking_lot.workspace = true
